"""initial schema

Revision ID: 6ab4e60ed2f1
Revises: 
Create Date: 2025-11-01 20:45:58.777599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab4e60ed2f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('level BETWEEN 0 AND 2', name='ck_activity_level_0_2'),
    sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_activity_parent')
    )
    op.create_index('ix_activity_name', 'activity', ['name'], unique=False)
    op.create_index('ix_activity_parent_level', 'activity', ['parent_id', 'level'], unique=False)
    op.create_table('building',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_lat_lon', 'building', ['lat', 'lon'], unique=False)
    op.create_table('organization',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_name', 'organization', ['name'], unique=False)
    op.create_table('office',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor', 'unit', name='uq_office_unique_in_building')
    )
    op.create_index('ix_office_building', 'office', ['building_id'], unique=False)
    op.create_table('organization_activity',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_index('ix_org_activity_activity', 'organization_activity', ['activity_id'], unique=False)
    op.create_table('organization_phone',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'phone_number', name='uq_org_phone_unique')
    )
    op.create_index('ix_org_phone_number', 'organization_phone', ['phone_number'], unique=False)
    op.create_index('ix_org_phone_org', 'organization_phone', ['organization_id'], unique=False)
    op.create_table('organization_office',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'office_id')
    )
    op.create_index('ix_org_office_office', 'organization_office', ['office_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_office_office', table_name='organization_office')
    op.drop_table('organization_office')
    op.drop_index('ix_org_phone_org', table_name='organization_phone')
    op.drop_index('ix_org_phone_number', table_name='organization_phone')
    op.drop_table('organization_phone')
    op.drop_index('ix_org_activity_activity', table_name='organization_activity')
    op.drop_table('organization_activity')
    op.drop_index('ix_office_building', table_name='office')
    op.drop_table('office')
    op.drop_index('ix_org_name', table_name='organization')
    op.drop_table('organization')
    op.drop_index('ix_building_lat_lon', table_name='building')
    op.drop_table('building')
    op.drop_index('ix_activity_parent_level', table_name='activity')
    op.drop_index('ix_activity_name', table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
